apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-catalog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-catalog-service
                port:
                  number: 8000
