apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
    labels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          envFrom:
          - configMapRef:
              name: book-catalog-config

          env:
          - name: DJANGO_SETTINGS_MODULE
            valueFrom:
              configMapKeyRef:
                name: book-catalog-config
                key: DJANGO_SETTINGS_MODULE

